### ISSUE TITLE
Using SwipeLayout without CoordinatorLayout

### ISSUE THREAD

**Issue by horse315** [xenione/SwipeLayout#5]
Hi!
I used SwipeLayout to make swipe panel and I wanted to animate translateTo() method, but there is no good way to do it. I'm missing point of extension in SwipeLayout so I can access orientationStrategy field.

**Comment by xenione** [comment]
Could you provide extra info about what you want to do.

**Comment by horse315** [comment]
I extended ```SwipeLayout```, added method ```translateToWithAnimation(int)```, which will create animation that calls public ```super::translateTo(int)``` method. But I can't determine current translationX/Y value, because ```SwipeLayout::orientationStrategy``` field is inaccessible.

**Comment by xenione** [comment]
You don't need to extend swipelayout. You can pass through a listener and be notify about translation ( you can get x or y as percentage ) and apply your transformations. See Swing example.

**Comment by horse315** [comment]
I'll try to explain what I'm doing in code. Here is very rough example:

```java
public class SwipeMakerAnimated extends SwipeLayout {
    public SwipeMakerAnimated(Context context) {
        super(context);
    }

    ...

    public void animatedTranslateTo(int position){
        // here orientationStrategy and getDelta are not accessable
        int currentPosition = orientationStrategy.getDelta();
        
        ValueAnimator animator = ValueAnimator.ofInt(currentPosition, position);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                int position = (int)animation.getAnimatedValue();
                SwipeMakerAnimated.this.translateTo(position);
            }
        });
    }
}
```

**Comment by xenione** [comment]
Better override onTranslateChange(...) There you can get the position X (percentage ) call super and apply animation
