### ISSUE TITLE
Invalid method overload called

### ISSUE THREAD

**Issue by horse315** [xenione/SwipeLayout#6]
Found a typo in amount of arguments [ScrollerHelper line 24](https://github.com/xenione/swipe-maker/blob/master/swipemaker/src/main/java/com/xenione/libs/swipemaker/ScrollerHelper.java#L24). Method with signature  ```OverScroller::startScroll(int startX, int startY, int dx, int dy)``` is called and ```SCROLL_ANIMATION_DURATION``` is passed as last argument ```dy```.

**Comment by xenione** [comment]
You are right. Try to fix ASAP.
