### ISSUE TITLE
Swipe left 

### ISSUE THREAD

**Issue by CeVague** [xenione/SwipeLayout#8]
When I create a list of "left swipe item" and I begin to scroll up or down in the list, each time I touch an item (I touch it just to do the scrolling action), it opened.
And it opened only one time. Once we close it t he bug disappears.

The code I use is :
`mForegroundView.anchor(0, -width_first_item, -(width_first_item + width_second_item) );`

And because my English is pretty bad, here is a video of the problem : [https://youtu.be/MAfllLtiGhk](https://youtu.be/MAfllLtiGhk)

**Comment by xenione** [comment]
it's your conctrete AbsCoordinatorLayout at the top of your View Hierarchy?

Please tell me more info about device and android version

**Comment by CeVague** [comment]
Oh yeah, sorry : 
I use android 6.0.1 on a "Asus ZenFone 2 ZE551ML"

Not sure what you mean by your first question.

But I had the same bug when I just modify your example application ("Two-steps Right Swipe") by just set others anchors (like presented above).
Strangely, it work well with a "One-step Left Swipe"

**Comment by xenione** [comment]
Thanks @CeVague I can reproduce the bug. I will fix as soon as I can.

**Comment by CeVague** [comment]
Perfect ^^
Good luck.

And thanks for this pretty good library.

**Comment by xenione** [comment]
fix it at version 1.1.3
